language: c

sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install texinfo

env:
  - t=$(mktemp -t -d)
  - p=$(pwd)

install: 
  - # check dependencies
  - make --version
  - gcc --version
  - ld --version
  - makeinfo --version
  - awk --version
  - perl --version
  - sed --version

  - cd "$t" && "$p"/configure --prefix=/usr
  - cd "$t" && make -f "$p"/Makefile
  - cd "$t" && make -f "$p"/Makefile check
