language: c

sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install texinfo

env:
  global:
    - t=$(mktemp -t -d)
    - p=$(pwd)

install: 
  - echo "t is '$t', p is '$p'"

  - # check dependencies
  - make --version
  - gcc --version
  - ld --version
  - makeinfo --version
  - awk --version
  - perl --version
  - sed --version

  - cd "$t" && "$p"/configure --prefix=/usr

  - ls -la "$t" | tee "$t"/.lsla
  - cat "$t"/[Mm]akefile*

  - cd "$t" && "$p"/travismake
  - cd "$t" && "$p"/travismake check || true # stop-on-test-failure=y

  - ls -la "$t" | diff "$t"/.lsla -
