language: c

sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install texinfo

install: 
  - # check dependencies
  - make --version
  - gcc --version
  - ld --version
  - texinfo --version
  - awk --version
  - perl --version
  - sed --version

  - t=$(mktemp -t -d) && p=$(pwd) && cd "$t" && $p/configure && make -f $p/Makefile && make -f $p/Makefile check
