language: c

sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install texinfo

env:
  global:
    - t=$(mktemp -t -d)
    - p=$(pwd)

install: 
  - echo "t is '$t', p is '$p'"

  - # check dependencies
  - make --version
  - gcc --version
  - ld --version
  - makeinfo --version
  - awk --version
  - perl --version
  - sed --version

  - cd "$t" && "$p"/configure --prefix=/usr
  - cd "$t" && make >make.log 2>&1 || { tail -n 500 make.log; false; }
  - cd "$t" && make check
