#!/bin/sh

set -eu

log=$(mktemp -t travismake.XXXXXXXXXXXX)
trap 'tail -n 500 "$log" /dev/null; rm -f "$log"' EXIT
trap 'exit 126' HUP INT TERM

make "$@" >"$log" 2>&1 &
m=$!

sh <<'____HERE' &
(
    tail -f "$log" &
    tailproc=$!
    while true; do
        date +'<><%T><>'
        sleep 300
    done &
    dateproc=$!
    trap 'kill $tailproc $dateproc' EXIT
    trap 'exit 126' HUP INT TERM
) | awk '/^<></ { t=$0; gsub(/[<>]/, "", t); n++; next; }
    ######## TODO: really kill if nothing happens for a really long time
    NR-n % 75 || NR-n > g+3 { g=NR-n; print t, $0 }'
____HERE

q=$!

wait "$m"
e=$?

kill "$q"

exit "$e"
